### ISSUE TITLE
xtend version not available

### ISSUE THREAD

**Issue by Huluvu424242** [svenefftinge/xtended_neo4j#1]
Hello, 

the xtend version 2.5.0-SNAPSHOT is not available in the general nexus of maven. But if you changed the version to 2.4.3 then the build will be work successful.

**Comment by svenefftinge** [comment]
Thanks, it should be 2.5.0 or 2.5.1-SNAPSHOT. Fixed it.

**Comment by Huluvu424242** [comment]
Sorry, does not work because in the nexus at https://repository.sonatype.org/ only available are:
eclipse.xtend.standalone-2.4.3
xtend-maven-plugin-2.5.0 and xtend-maven-plugin-2.4.3
So only 2.4.3 will be work.
